name: ✨ Feature request
description: Suggest an enhancement, improvement or idea
labels: ["type:enhancement", "awaiting-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the motivation or use case for this enhancement?
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired behavior
      description: How would the feature work and what would it look like?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other relevant information about the feature request.
